# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigc_copyright?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  redis:
    host: 121.196.234.221
    port: 6379
    password: 123456
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    database: 0

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MyBatis Flex
mybatis-flex:
  mapper-package: com.blockchain.aigc.mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blockchain.aigc.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# MinIO配置
minio:
  endpoint: http://121.196.234.221:9000
  access-key: minioadmin
  secret-key: 12345678
  bucket-name: aigc-works

# JWT配置
jwt:
  secret: aigc-copyright-system-secret-key-2025
  expiration: 86400000

# 区块链配置

# 日志配置
logging:
  level:
    com.blockchain.aigc: debug
    org.springframework.security: debug


contract:
  address-action: 0xfa6ac41d0e064cfb50321de940cd7a7907b2dede
