cryptoMaterial:
  useSMCrypto: false
  certPath: "conf"
  caCert: "conf/ca.crt"
  sslCert: "conf/sdk.crt"
  sslKey: "conf/sdk.key"
#  enSslCert: "conf/sm_ensdk.crt"
#  enSslKey: "conf/sm_ensdk.key"

#  enableHsm: false
#  hsmLibPath: "/usr/local/lib/libgmt0018.so"
#  hsmKeyIndex: "1"
#  hsmPassword: "12345678"

network:
  defaultGroup: "group0"
  peers:
    - "127.0.0.1:59796"
    - "127.0.0.1:34778"
    - "127.0.0.1:30303"
#    - "127.0.0.1:20201"
#    - "127.0.0.1:20200"

amop:
#  - publicKeys: [ "conf/amop/consumer_public_key_1.pem" ]
#    topicName: "PrivateTopic1"
#  - password: "123456"
#    privateKey: "conf/amop/consumer_private_key.p12"
#    topicName: "PrivateTopic2"

account:
  keyStoreDir: "account"
  #  accountFilePath: "conf"
  accountFileFormat: "pem"
#  accountAddress: "0x"
#  password: ""


threadPool:
#  threadPoolSize: "16"
